---
name: Build for PyPi

on:
  workflow_call:

permissions:
  contents: read

jobs:
  build_for_pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install dependencies
        run: pip install uv

      - name: Build sdist and bdist 
        run: |
          cd codecov-cli
          uv build

      - name: Store the distributions
        uses: actions/upload-artifact@v4
        with:
          name: codecov-cli-dist
          path: ./codecov-cli/dist/*
