name: CLI CI Job

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build-test-upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install dependencies
      run: |
        python -m pip install uv
        uv sync --project codecov-cli
        uv sync --project prevent-cli

    - name: Test with pytest
      run: |
        cd codecov-cli
        uv run pytest --cov --junitxml=3.12junit.xml
      env:
        CODECOV_ENV: test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        flags: python3.12
        fail_ci_if_error: true
        verbose: true
