name: CLI CI Job

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-test-upload:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 2
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        cd codecov-cli
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python -m pip install -e .
        pip install -r tests/requirements.txt
    - name: Test with pytest
      run: |
        cd codecov-cli
        pytest --cov --junitxml=3.12junit.xml
      env:
        CODECOV_ENV: test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./coverage.xml
        flags: python3.12
        fail_ci_if_error: true
        verbose: true
