name: Create CLI Release PR

on:
  # workflow_dispatch:
  #   inputs:
  #     versionName:
  #       description: 'Name of version  (ie 23.9.5)'
  #       required: true
  push

jobs:
  create-release-pr:
    name: Create PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # todo: add this back? or not?
      # - name: Import GPG key
      #   id: import-gpg
      #   uses: crazy-max/ghaction-import-gpg@v6
      #   with:
      #     gpg_private_key: ${{ secrets.RELEASER_GPG_PRIVATE_KEY }}
      #     git_user_signingkey: true
      #     git_commit_gpgsign: true
      #     git_config_global: true

      - name: Create release branch
        #run: git checkout -b release/${{ github.event.inputs.versionName }}
        run: git checkout -b test-sentry-release-bot

      - name: Set bot's Git info
        run: |
          git config --global user.email "180476844+sentry-release-bot[bot]@users.noreply.github.com"
          git config --global user.name "sentry-release-bot[bot]"

      - name: Update version and push
        id: make-commit
        run: |
          cd codecov-cli
          # sed -i 's/version\ =\ "[0-9]\+\.[0-9]\+\.[0-9]\+"/version\ =\ "${{ github.event.inputs.versionName }}"/g' pyproject.toml
          sed -i 's/version\ =\ "[0-9]\+\.[0-9]\+\.[0-9]\+"/version\ =\ "test"/g' pyproject.toml
          git add pyproject.toml
          #git commit --message "Prepare release ${{ github.event.inputs.versionName }}"
          git commit --message "test"
          echo "commit=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
          #git push origin release/${{ github.event.inputs.versionName }}
          git push origin test-sentry-release-bot

      - name: Get auth token
        id: token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        with:
          app-id: ${{ vars.SENTRY_RELEASE_BOT_CLIENT_ID }}
          private-key: ${{ secrets.SENTRY_RELEASE_BOT_PRIVATE_KEY }}

      - name: Create pull request into main
        uses: thomaseizinger/create-pull-request@1.3.1
        with:
          github_token: ${{ steps.token.outputs.token }}
          # head: release/${{ github.event.inputs.versionName }}
          head: test-sentry-release-bot
          base: main
          # title: Release ${{ github.event.inputs.versionName }}
          title: Test pr
          reviewers: ${{ github.event.issue.user.login }}
          # body: |
          #   Release PR for ${{ github.event.inputs.versionName }}
          #   I've updated the version name and committed: ${{ steps.make-commit.outputs.commit }}.
          body: test body
