name: Create CLI Release PR

on:
  workflow_dispatch:
    inputs:
      versionName:
        description: 'Name of version  (ie 23.9.5)'
        required: true

permissions:
  contents: write

jobs:
  create-release-pr:
    name: Create PR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set sentry-release-bot's Git info
        run: |
          git config --global user.email "180476844+sentry-release-bot[bot]@users.noreply.github.com"
          git config --global user.name "sentry-release-bot[bot]"

      - name: Create release branch
        run: git checkout -b release/"$VERSION_NAME"
        env:
          VERSION_NAME: ${{ github.event.inputs.versionName }}

      - name: Update version and push
        id: make-commit
        run: |
          sed -i "s/version\ =\ \"[0-9]\+\.[0-9]\+\.[0-9]\+\"/version\ =\ \"$VERSION_NAME\"/g" codecov-cli/pyproject.toml
          pip install uv
          uv sync --project codecov-cli # updates uv.lock
          uv sync --project prevent-cli
          git add .
          git commit --message "Prepare release $VERSION_NAME"
          echo "commit=$(git rev-parse HEAD)" >> "$GITHUB_OUTPUT"
          git push origin release/"$VERSION_NAME"
        env:
          VERSION_NAME: ${{ github.event.inputs.versionName }}

      - name: Get auth token
        id: token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        with:
          app-id: ${{ vars.SENTRY_RELEASE_BOT_CLIENT_ID }}
          private-key: ${{ secrets.SENTRY_RELEASE_BOT_PRIVATE_KEY }}

      - name: Create pull request into main
        uses: thomaseizinger/create-pull-request@1.3.1
        with:
          github_token: ${{ steps.token.outputs.token }}
          head: release/${{ github.event.inputs.versionName }}
          base: main
          title: Release ${{ github.event.inputs.versionName }}
          reviewers: ${{ github.event.issue.user.login }}
          body: |
            Release PR for ${{ github.event.inputs.versionName }}
            I've updated the version name and committed: ${{ steps.make-commit.outputs.commit }}.
