# This workflow publishes the codecov-cli assets to PyPI, GitHub releases, and
# our GCS bucket when a release is created.
name: Build and publish codecov-cli

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  # publish_to_pypi:
  #   needs: build_for_pypi
  #   permissions:
  #     id-token: write # This is required for OIDC
  #   runs-on: ubuntu-latest
  #   environment:
  #     name: pypi
  #     url: https://pypi.org/p/codecov-cli
  #   steps:
  #     - name: Download build artifacts
  #       uses: dawidd6/action-download-artifact@ac66b43f0e6a346234dd65d4d0c8fbb31cb316e5 # v11
  #       with:
  #         branch: release/${{ github.ref }}
  #         name: codecov-cli_wheel
  #         path: codecov-cli/dist
  #
  #     - name: Publish package to PyPi
  #       uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc # v1.12.4
  #       with:
  #         verbose: true
  #         packages-dir: codecov-cli/dist

  publish_to_github:
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifacts
        uses: dawidd6/action-download-artifact@ac66b43f0e6a346234dd65d4d0c8fbb31cb316e5 # v11
        with:
          branch: release/${{ github.ref }}
          name: codecov.*
          name_is_regexp: true
          path: codecov-cli/dist

      - name: Get auth token
        id: token
        uses: actions/create-github-app-token@df432ceedc7162793a195dd1713ff69aefc7379e # v2.0.6
        with:
          app-id: ${{ vars.SENTRY_RELEASE_BOT_CLIENT_ID }}
          private-key: ${{ secrets.SENTRY_RELEASE_BOT_PRIVATE_KEY }}

      - name: Upload Release Asset
        id: upload-release-asset
        uses: svenstaro/upload-release-action@81c65b7cd4de9b2570615ce3aad67a41de5b1a13 # v2.11.2
        with:
          repo_token: ${{ steps.token.outputs.token }}
          file_glob: true
          file: ./codecov-cli/dist/*
          tag: ${{ github.ref }}
          overwrite: true

  # publish_release:
  #   name: Publish release
  #   needs: [build_assets, build_linux_assets, build_for_pypi, publish_to_pypi]
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: "read"
  #     id-token: "write"
  #   steps:
  #     - id: "auth"
  #       name: "Authenticate to Google Cloud"
  #       uses: "google-github-actions/auth@v1.0.0"
  #       with:
  #         create_credentials_file: "true"
  #         workload_identity_provider: ${{ secrets.CODECOV_GCP_WIDP }}
  #         service_account: ${{ secrets.CODECOV_GCP_WIDSA }}
  #
  #     # Publish the release tag to a Pub/Sub topic
  #     - name: Publish a message to a Pub/Sub topic
  #       env:
  #         CLOUDSDK_CORE_PROJECT: ${{ secrets.GCLOUD_UPLOADER_PROJECT_ID }}
  #       run: |
  #         gcloud pubsub topics publish ${{ secrets.GCLOUD_UPLOADER_PUBSUB_TOPIC }} --message '{"release":"'"${{ github.ref_name }}"'", "latest":true}'
