name: Test workflow

on:
  push

jobs: 
  build_for_pypi:
    permissions:
      id-token: write # This is required for requesting the JWT
      contents: read  # This is required for actions/checkout
    uses: ./.github/workflows/build_for_pypi.yml
    with:
      publish: false # todo: back to true when tested
    secrets: inherit

  buildassets:
    name: Build packages
    uses: ./.github/workflows/build_assets.yml
    with:
      release: false # todo: back to true when tested
    secrets: inherit
